In [2]:
import torch

In [4]:
print(torch.backends.mps.is_available())
print(torch.rand(2,2))

True
tensor([[0.3449, 0.8401],
        [0.8748, 0.9489]])


In [6]:
x = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
x

tensor([[1., 2.],
        [3., 4.]])

In [7]:
x[0, 0] = 10
x

tensor([[10.,  2.],
        [ 3.,  4.]])

In [8]:
torch.zeros(2, 2)


tensor([[0., 0.],
        [0., 0.]])

In [9]:
torch.ones(2, 2)    

tensor([[1., 1.],
        [1., 1.]])

In [11]:
y = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
z = x + y
z

tensor([[11.,  4.],
        [ 6.,  8.]])

In [12]:
torch.rand(1).item()

0.11014890670776367

In [15]:
cpu_tensor = torch.rand(2)

In [16]:
cpu_tensor.device

device(type='cpu')

In [17]:
gpu_tensor = cpu_tensor.to("mps")

In [18]:
gpu_tensor.device

device(type='mps', index=0)

In [19]:
torch.rand(2, 2).max()

tensor(0.9892)

In [20]:
torch.rand(2, 2).max().item()

0.5177492499351501

In [23]:
long_tensor = torch.tensor([1, 2, 3], dtype=torch.long)
type(long_tensor.max().item())
long_tensor.type()

'torch.LongTensor'

In [25]:
float_tensor = long_tensor.to(torch.float32)
type(float_tensor.max().item())
float_tensor.type()

'torch.FloatTensor'

In [31]:
rand_tensor = torch.rand(2, 2)
rand_tensor.log2()
rand_tensor


tensor([[0.1475, 0.9839],
        [0.6403, 0.2027]])

In [32]:
rand_tensor.log2_()
rand_tensor

tensor([[-2.7609, -0.0235],
        [-0.6433, -2.3026]])

In [33]:
rand_tensor.log2_()
rand_tensor

tensor([[nan, nan],
        [nan, nan]])

In [30]:
# Crie o tensor uma única vez
rand_tensor = torch.rand(2, 2)
print("Tensor original:")
print(rand_tensor)

# Aplique a primeira operação in-place
rand_tensor.log2_()
print("\nApós a primeira aplicação de log2_:")
print(rand_tensor)

# Aplique a segunda operação in-place
rand_tensor.log2_()
print("\nApós a segunda aplicação de log2_:")
print(rand_tensor)

Tensor original:
tensor([[0.3423, 0.4404],
        [0.6798, 0.2512]])

Após a primeira aplicação de log2_:
tensor([[-1.5468, -1.1832],
        [-0.5569, -1.9933]])

Após a segunda aplicação de log2_:
tensor([[nan, nan],
        [nan, nan]])


In [34]:
flat_tensor = torch.rand(784)

In [41]:
viewed_tensor = flat_tensor.view(1, 28, 28)
viewed_tensor.shape
viewed_tensor

tensor([[[1.3521e-01, 2.5439e-02, 3.2872e-02, 3.6915e-02, 9.0117e-02,
          2.5058e-01, 1.6621e-01, 7.2529e-01, 2.2829e-01, 8.0644e-01,
          9.4804e-01, 3.0500e-01, 5.5119e-01, 9.2415e-01, 4.1744e-01,
          6.4949e-01, 9.7516e-01, 7.8303e-01, 9.8324e-01, 1.6930e-01,
          2.1817e-01, 8.8802e-02, 5.7092e-02, 5.7030e-01, 4.8206e-01,
          5.9191e-02, 8.3078e-01, 2.0842e-01],
         [1.5101e-01, 8.4226e-01, 5.1099e-01, 3.6959e-01, 9.1619e-02,
          1.8469e-01, 5.7005e-02, 2.1295e-01, 3.8683e-01, 6.2004e-01,
          8.2211e-01, 5.1584e-01, 8.8292e-01, 3.3959e-01, 4.7446e-01,
          5.0996e-02, 4.9984e-01, 1.3148e-01, 3.2382e-01, 6.4101e-01,
          6.5445e-01, 1.2752e-01, 5.9579e-01, 6.0315e-02, 2.5956e-01,
          5.9275e-01, 8.2118e-01, 6.0060e-01],
         [5.2634e-01, 3.2284e-01, 9.7496e-01, 2.9235e-01, 2.3806e-01,
          2.0024e-02, 3.0056e-01, 1.6136e-02, 5.8412e-02, 1.1839e-01,
          1.1961e-01, 8.2130e-01, 9.7780e-01, 8.1076e-02, 6.5387e-

In [42]:
reshaped_tensor = viewed_tensor.reshape(1, 28, 28)
reshaped_tensor.shape


torch.Size([1, 28, 28])

In [43]:
hwc_tensor = torch.rand(32, 15, 3)
chw_tensor = hwc_tensor.permute(2, 0, 1)
chw_tensor.shape

torch.Size([3, 32, 15])